import 'package:eurovision_app/app/common/constants/app_icons.dart';

class CountryIconProvider {
  static const Map<String, String> countryIcons = {
    "AL": AppIcons.alFlag,
    "AD": AppIcons.adFlag,
    "AM": AppIcons.amFlag,
    "AU": AppIcons.auFlag,
    "AT": AppIcons.atFlag,
    "AZ": AppIcons.azFlag,
    "BY": AppIcons.byFlag,
    "BE": AppIcons.beFlag,
    "BA": AppIcons.baFlag,
    "BG": AppIcons.bgFlag,
    "HR": AppIcons.hrFlag,
    "CY": AppIcons.cyFlag,
    "CZ": AppIcons.czFlag,
    "DK": AppIcons.dkFlag,
    "EE": AppIcons.eeFlag,
    "FI": AppIcons.fiFlag,
    "FR": AppIcons.frFlag,
    "GE": AppIcons.geFlag,
    "DE": AppIcons.deFlag,
    "GR": AppIcons.grFlag,
    "HU": AppIcons.huFlag,
    "IS": AppIcons.isFlag,
    "IE": AppIcons.ieFlag,
    "IL": AppIcons.ilFlag,
    "IT": AppIcons.itFlag,
    "KZ": AppIcons.kzFlag,
    "LV": AppIcons.lvFlag,
    "LT": AppIcons.ltFlag,
    "LU": AppIcons.luFlag,
    "MT": AppIcons.mtFlag,
    "MD": AppIcons.mdFlag,
    "MC": AppIcons.mcFlag,
    "ME": AppIcons.meFlag,
    "MA": AppIcons.maFlag,
    "NL": AppIcons.nlFlag,
    "MK": AppIcons.mkFlag,
    "NO": AppIcons.noFlag,
    "PL": AppIcons.plFlag,
    "PT": AppIcons.ptFlag,
    "RO": AppIcons.roFlag,
    "RU": AppIcons.ruFlag,
    "SM": AppIcons.smFlag,
    "RS": AppIcons.rsFlag,
    "CS": AppIcons.csFlag,
    "SK": AppIcons.skFlag,
    "SI": AppIcons.siFlag,
    "ES": AppIcons.esFlag,
    "SE": AppIcons.seFlag,
    "CH": AppIcons.chFlag,
    "TR": AppIcons.trFlag,
    "UA": AppIcons.uaFlag,
    "GB": AppIcons.gbFlag,
    "GB-WLS": AppIcons.gbWlsFlag,
    "YU": AppIcons.yuFlag
  };

  String getIconPath(String countryCode) {
    return countryIcons[countryCode] ?? 'assets/icons/flags/tr.svg';
  }
}
